"""draft_closed_at

Revision ID: d29079db5197
Revises: 3100bfa20342
Create Date: 2025-11-08 14:44:21.614989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29079db5197'
down_revision: Union[str, Sequence[str], None] = '3100bfa20342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'closed_at')
    # ### end Alembic commands ###
